// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package ip

const TableNameIP = "ip"

// IP mapped from table <ip>
type IP struct {
	ID      int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:ID" json:"id"`
	Address string `gorm:"column:address;type:character varying;not null;comment:IP 地址" json:"address"`
	Status  Status `gorm:"column:status;type:character varying;not null;comment:状态" json:"status"`
	Latency int64  `gorm:"column:latency;type:bigint;not null;comment:延迟" json:"latency"`
	Source  string `gorm:"column:source;type:character varying;not null;comment:来源" json:"source"`
}

// TableName IP's table name
func (*IP) TableName() string {
	return TableNameIP
}
